# Generated by Django 4.2.5 on 2024-02-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_authuser_last_login_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(default='', null=True, verbose_name='登陆ip'),
        ),
    ]
