# Generated by Django 4.2.10 on 2024-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_alter_authuser_last_login_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="port",
            field=models.IntegerField(default=22, verbose_name="端口号"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="port_server",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="端口的协议类型"
            ),
        ),
    ]
