# Generated by Django 4.2.10 on 2024-03-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_iottaskfingerresult_port_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iottaskfingerresult",
            old_name="port_server",
            new_name="port_service",
        ),
    ]
