# Generated by Django 4.2.10 on 2024-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0006_rename_port_server_iottaskfingerresult_port_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="scan_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="端口的协议类型"
            ),
        ),
    ]
