# Generated by Django 4.2.10 on 2024-03-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0007_iottaskfingerresult_scan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iottaskfingerresult",
            name="scan_type",
            field=models.CharField(
                default="tcp", max_length=10, verbose_name="端口的协议类型"
            ),
            preserve_default=False,
        ),
    ]
