# Generated by Django 4.2.10 on 2024-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0008_alter_iottaskfingerresult_scan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                default=None, null=True, verbose_name="登陆ip"
            ),
        ),
    ]
