# Generated by Django 4.2.10 on 2024-03-14 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0009_alter_authuser_last_login_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="authuser",
            name="api_key",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                verbose_name="用户api接口key",
            ),
        ),
        migrations.AlterField(
            model_name="iottaskfingerresult",
            name="scan_type",
            field=models.CharField(max_length=10, verbose_name="扫描类型"),
        ),
    ]
