# Generated by Django 4.2.10 on 2024-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0010_authuser_api_key_alter_iottaskfingerresult_scan_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iottaskfingerresult",
            old_name="res_headers",
            new_name="headers",
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="city",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="ip城市",
            ),
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="ip国家",
            ),
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="isp",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="ip运营商",
            ),
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="province",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="ip省份",
            ),
        ),
        migrations.AddField(
            model_name="iottaskfingerresult",
            name="region",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="ip区域",
            ),
        ),
    ]
