# Generated by Django 4.2.10 on 2024-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0011_rename_res_headers_iottaskfingerresult_headers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IotTaskSensitiveInformation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="url地址",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="url信息",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "备份文件"), (1, "敏感信息")],
                        default=1,
                        verbose_name="数据类型",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
            ],
        ),
    ]
