# Generated by Django 4.2.10 on 2024-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0012_iottasksensitiveinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetmanager",
            name="is_domain",
            field=models.BooleanField(default=False, verbose_name="是否收集子域名"),
        ),
    ]
