# Generated by Django 4.2.10 on 2024-04-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0013_targetmanager_is_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iottasksensitiveinformation",
            name="type",
            field=models.IntegerField(
                choices=[(1, "敏感信息"), (0, "备份文件")],
                default=1,
                verbose_name="数据类型",
            ),
        ),
        migrations.AlterField(
            model_name="targetmanager",
            name="status",
            field=models.IntegerField(
                choices=[
                    (-1, "停止"),
                    (0, "初始化"),
                    (1, "运行中"),
                    (2, "完成"),
                    (3, "删除"),
                    (4, "失败"),
                    (5, "未知错误"),
                ],
                default=0,
                verbose_name="任务状态",
            ),
        ),
    ]
