# Generated by Django 4.2.10 on 2024-04-11 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0014_alter_iottasksensitiveinformation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iottasksensitiveinformation",
            name="type",
            field=models.IntegerField(
                choices=[(0, "备份文件"), (1, "敏感信息")],
                default=1,
                verbose_name="数据类型",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="poc_name",
            field=models.TextField(db_index=True, verbose_name="poc名称"),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vul_author",
            field=models.CharField(
                max_length=100, null=True, verbose_name="poc作者名字"
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vul_createDate",
            field=models.DateField(
                default=django.utils.timezone.now, null=True, verbose_name="poc编写时间"
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vul_updateDate",
            field=models.DateField(
                default=django.utils.timezone.now, null=True, verbose_name="poc更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vul_vulDate",
            field=models.DateField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="漏洞公开日期",
            ),
        ),
    ]
