# Generated by Django 4.2.10 on 2024-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0015_alter_iottasksensitiveinformation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iottasksensitiveinformation",
            name="type",
            field=models.IntegerField(
                choices=[(1, "敏感信息"), (0, "备份文件")],
                default=1,
                verbose_name="数据类型",
            ),
        ),
    ]
