# Generated by Django 4.2.10 on 2024-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0016_alter_iottasksensitiveinformation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iottasksensitiveinformation",
            name="type",
            field=models.IntegerField(
                choices=[(0, "备份文件"), (1, "敏感信息")],
                default=1,
                verbose_name="数据类型",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerability",
            name="vul_author",
            field=models.CharField(
                max_length=50, null=True, verbose_name="poc作者名字"
            ),
        ),
    ]
